# Generated by Django 2.1 on 2017-12-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='asset_type',
            field=models.IntegerField(null=2),
        ),
    ]
