# Generated by Django 2.1 on 2017-12-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_record_asset_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='asset_type',
        ),
        migrations.AddField(
            model_name='record',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
