# Generated by Django 2.1 on 2017-12-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_record_shirt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='asset_type',
            field=models.IntegerField(choices=[(0, '笔记本或台式机'), (1, '服务器'), (2, '其他设备')], default=0, help_text='请选择设备类型', max_length=1),
        ),
        migrations.AlterField(
            model_name='record',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', help_text='这是帮助内容', max_length=1),
        ),
    ]
