# Generated by Django 2.1 on 2017-12-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20171226_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='asset_number',
            field=models.CharField(help_text='一般为设备位移识别码', max_length=200, null=True, verbose_name='资产编号'),
        ),
        migrations.AlterField(
            model_name='record',
            name='asset_type',
            field=models.IntegerField(choices=[(0, '笔记本或台式机'), (1, '服务器'), (2, '其他设备')], default=0, max_length=1, verbose_name='资产类型'),
        ),
    ]
