# Generated by Django 2.1 on 2017-12-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20171226_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='asset_status',
            field=models.BooleanField(choices=[(True, '完好'), (False, '故障')], default=True, verbose_name='设备状态'),
        ),
        migrations.AddField(
            model_name='record',
            name='buy_date',
            field=models.DateTimeField(null=True, verbose_name='采购时间'),
        ),
        migrations.AddField(
            model_name='record',
            name='conf_info',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='配置信息'),
        ),
        migrations.AddField(
            model_name='record',
            name='get_time',
            field=models.DateTimeField(null=True, verbose_name='领用时间'),
        ),
        migrations.AddField(
            model_name='record',
            name='send_user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='发送人'),
        ),
        migrations.AddField(
            model_name='record',
            name='store_place',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='存放地点'),
        ),
        migrations.AddField(
            model_name='record',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='领用人'),
        ),
        migrations.AlterField(
            model_name='record',
            name='asset_number',
            field=models.CharField(help_text='一般为设备唯一识别码', max_length=200, null=True, verbose_name='资产编号'),
        ),
        migrations.AlterField(
            model_name='record',
            name='asset_type',
            field=models.IntegerField(choices=[(0, '笔记本或台式机'), (1, '服务器'), (2, '其他设备')], default=0, verbose_name='资产类型'),
        ),
    ]
