# Generated by Django 2.1 on 2017-12-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20171226_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='asset_status',
        ),
    ]
