# Generated by Django 2.1 on 2017-12-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_remove_record_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='asset_type',
            field=models.IntegerField(choices=[(0, '笔记本或台式机2'), (1, '服务器'), (2, '其他设备')], default=0, verbose_name='资产类型'),
        ),
        migrations.AlterField(
            model_name='record',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium2'), ('L', 'Large')], default='M', help_text='这是帮助内容', max_length=1),
        ),
    ]
