# Generated by Django 2.1 on 2017-12-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_auto_20171227_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='asset_number',
        ),
        migrations.RemoveField(
            model_name='record',
            name='buy_date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='conf_info',
        ),
        migrations.RemoveField(
            model_name='record',
            name='content_text',
        ),
        migrations.RemoveField(
            model_name='record',
            name='get_time',
        ),
        migrations.RemoveField(
            model_name='record',
            name='send_date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='send_user',
        ),
        migrations.RemoveField(
            model_name='record',
            name='shirt_size',
        ),
        migrations.RemoveField(
            model_name='record',
            name='store_place',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user_name',
        ),
    ]
