# Generated by Django 2.1 on 2017-12-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_auto_20171227_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='asset_number',
            field=models.CharField(help_text='一般为设备唯一识别码', max_length=200, null=True, verbose_name='资产编号'),
        ),
    ]
