# Generated by Django 2.1 on 2017-12-27 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_record_asset_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='buy_date',
            field=models.DateTimeField(null=True, verbose_name='采购时间'),
        ),
        migrations.AddField(
            model_name='record',
            name='conf_info',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='配置信息'),
        ),
        migrations.AddField(
            model_name='record',
            name='content_text',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='get_time',
            field=models.DateTimeField(null=True, verbose_name='领用时间'),
        ),
        migrations.AddField(
            model_name='record',
            name='send_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发放时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='send_user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='发送人'),
        ),
        migrations.AddField(
            model_name='record',
            name='store_place',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='存放地点'),
        ),
        migrations.AddField(
            model_name='record',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='领用人'),
        ),
    ]
