# Generated by Django 2.1 on 2017-12-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.IntegerField(default=0),
        ),
    ]
